Add step to update setuptools to DEVELOP.rst
Older setuptools versions can cause an error along the lines of:

     File ".../crate-docs-theme/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2120, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'